### ISSUE TITLE
Supporting adding a new subdomain

### ISSUE THREAD

**Issue by aaomidi** [adferrand/docker-letsencrypt-dns#2]
In `domains.conf` if a sub domain is added to the file later the container doesn't handle that properly.

Is there a way we can handle that?

**Comment by adferrand** [comment]
Thanks for your report.

This container is designed to watch modifications of `domains.conf` when running, and regenerate certificates if needed. During my tests, on a up-to-date ArchLinux (kernel 4.12) and Docker 17.06, this feature is working properly.

Could you give me more details about what is not working ? Is it the modification not detected, or certbot fails to regenerate the certificates ?

Could you also give me the container execution environment ? OS type and version, Docker version, logs of the running container.

Thanks in advance.
Adrien Ferrand

**Comment by adferrand** [comment]
In 1.2.0 version I changed my approach to watch `domains.conf`. It was based on the inotify tool, by I appeared that inode events were not always correctly propagated in the Docker environment, leading to not notice a `domains.conf` update. I moved to a good old infinite loop, checking for updates on `domains.conf` every second.

It will work on any environment, and assume that this issue is resolved.

Do not hesitate to reopen it if it is not the case.

Regards,
Adrien Ferrand
