### ISSUE TITLE
Removes/ revokes certs after success

### ISSUE THREAD

**Issue by sysrazor** [adferrand/docker-letsencrypt-dns#23]
Not sure if there is a flag I missed; I am seeing an issue where after a successful cert it then revokes and deletes the cert.

**Comment by adferrand** [comment]
Could you provide the domains.conf and the container log to see what happened ? Some people saw a bug before, where in some cases my container would not see the first line of domains.conf, and would assume with a one line file that everything was removed from configuration, and so the certificates should be removed.

Normally it is corrected so be sure to use the latest version, but I will check the behavior with your log.

**Comment by adferrand** [comment]
Thank you, I found the problem. File domains.conf was parsed correctly during certificates creation phrase, but not during certificates revocation phase.

Version 2.5.0 is on its way, and corrects this issue.

**Comment by sysrazor** [comment]
Just updated to 2.5.0 and looks to still be unresolved. Attached are latest log files.

[LE-Log1.txt](https://github.com/adferrand/docker-letsencrypt-dns/files/2219848/LE-Log1.txt)

[dockerLog.txt](https://github.com/adferrand/docker-letsencrypt-dns/files/2219856/dockerLog.txt)

**Comment by adferrand** [comment]
Hello, sorry for the delay, I am on hollydays...

Could you provide me your domains.conf? It needs to be the exact file you try to use, not a copy of its content, in order to allow me to check against encoding issues.

**Comment by adferrand** [comment]
Hello, I made a new version for a similar problem (#26). Could you say to me if your bug is correct with the latest version (2.5.1) ?

**Comment by sysrazor** [comment]
looks like its still failing on 2.5.2

**Comment by adferrand** [comment]
OK, I got it! In you domains.conf, you have declared your domains separated by a comma, while they should be separated by a space.

Even if it works for certbot because it accepts multiple domains separated by commas in a single 
 -d option, it will not work with my scripts when they verify if a certificate needs to be revoked.

Use spaces instead of commas to solve you issue. 

I am quite aware that the weak formatting of domains.conf becomes a problem. I am working on a new version way more stable and modulable, using python scripts and yaml configuration files.

**Comment by adferrand** [comment]
I assume the issue is closed. Do not hesitate to reopen if it does not work.

**Comment by Holly-Marie** [comment]
I encountered the same effect. Certs would be successfuly requested and stored and at the end got revoked again.

After reading here that the domains.conf may be the problem I checked it again.

Turns out that with coping through a windows system, the line endings had been turned into **windows line entings (CR LF)**. So I converted the line endings to **unix (LF)** and that fixed the problem.

Note:
I used Notepad++ through WinScp to: Edit->EOL Conversions->Unix (LF) on domains.conf
