### ISSUE TITLE
Changes to domains.conf are not propagating into container

### ISSUE THREAD

**Issue by loganto** [adferrand/docker-letsencrypt-dns#34]
Changes to domains.conf are not propagating into container after start.

So when I've edited domains.conf -> new cert wasn't created so went and checked  on what's in the container and domains.conf didnt have a new domain listed.  

This is how I launch the container:  

```
docker run -d \
    --name letsencrypt-dns \
    --restart=always \
    --volume /mnt/dockers/domains/domains.conf:/etc/letsencrypt/domains.conf \
    --volume /mnt/dockers/certs:/etc/letsencrypt \
    --env 'LETSENCRYPT_USER_MAIL=MY_EMAIL' \
    --env 'LEXICON_PROVIDER=MY_PROVIDER' \
    --env 'LEXICON_NAMESILO_USERNAME=MY_USERNAME' \
    --env 'LEXICON_NAMESILO_TOKEN=MY_TOKEN' \
    --env 'LEXICON_SLEEP_TIME=960' \
    adferrand/letsencrypt-dns
```

is it possible to configure `/etc/letsencrypt/domains.conf` to use some subdirectory like `/etc/letsencrypt/domains/domains.conf` ?

**Comment by adferrand** [comment]
Hello!

So if I understand correctly, you mounted directly `domains.conf` into the container, and when you edit it with the container enabled, it does not see the change and does not trigger the certificate request. Right?

I will test this configuration today to see if I can catch something. In the mean time, can you paste me the container log when you make an edition on `domain.conf`?

I think you did this configuration for a specific purpose, but I wanted to remind you that usually, you want to mount the entire `/etc/letsencrypt` folder, in order to be able to access the certificates from the host, and that you edit `domains.conf` from the host inside the mounted folder.

**Comment by adferrand** [comment]
And now that I think of it, there could be the problem. Even if you do not mount `/etc/letsencrypt` folder, it is declared as a Docker volume. So it shadow any pre existing content at this path when the container start, and maybe also it shadow any further explicit mount of files into that folder. So in fact the container would not see your edited `domains.conf` because what it see, it is another `domains.conf`, created by the container into `/etc/letsencrypt`.

I will check that definitively.

**Comment by adferrand** [comment]
So it leads me to the other request you have, and that could solve this specific problem. Mount and read `domains.conf` from another path, and for you preferably outside of `/etc/letsencrypt`.

Quite easy in fact, I will expose an environment variable to define a custom path in the next version.

**Comment by loganto** [comment]
> I think you did this configuration for a specific purpose, but I wanted to remind you that usually, you want to mount the entire /etc/letsencrypt folder, in order to be able to access the certificates from the host, and that you edit domains.conf from the host inside the mounted folder.

I mean - the only reason I mount `domains.conf` directly into container - is because this is how it's described in the documentation: https://github.com/adferrand/docker-letsencrypt-dns#share-certificates-with-the-host

**Comment by loganto** [comment]
> Mount and read domains.conf from another path, and for you preferably outside of /etc/letsencrypt

I mean - ya - on the host I can put `domains.conf` in any location. But the problem is the way I see it -> internally inside of the container -  `domains.conf` is expected under `/etc/letsencrypt` only which leads to overlapping of mounted volumes:
```
--volume /mnt/dockers/domains/domains.conf:/etc/letsencrypt/domains.conf \
--volume /mnt/dockers/certs:/etc/letsencrypt \
```

Is there a way to put `domains.conf ` into different location inside of a container?

**Comment by adferrand** [comment]
Ok. I did some tests, and indeed, if you mount both volumes, there is two `domains.conf`. The one from `/etc/letsencrypt` and the one directly mounted from the host. The latter take precedence over the former.

What you are revealing is two things:
- first, my `README.md` should not advice to mount `domains.conf` directly, because later this would create the result I described when you host mount `/etc/letsencrypt` itself
- second, this is a big flaw in the design of my Docker, I should not have specified `/etc/letsencrypt/domains.conf` as the path for the configuration, but something different.

So for the `README.md`, I will correct that. For the design, well, a environment variable specifying where the container should find `domains.conf` would correct the problem.

However, I am quite reluctant to do that. Mainly because this becomes part of the several flaws I would like to correct by implementing the new architecture I specified here: https://github.com/adferrand/docker-letsencrypt-dns/wiki/Project-V3-specifications

It is a complete redesign, that will include to put the configuration file in a specific place separated from `/etc/letsencrypt`.

As a consequence, if you do not mind, I would like to correct this issue in the scope of the new architecture, which should be ready in few weeks. In the mean time, you should make a correction from your host: do not mount directly `domains.conf`, use the directory `/etc/letsencrypt`. If you need to specify `domains.conf` in a different place in your host, you should use a symbolic link or a bind mount to put a reference of the file in `/etc/letsencrypt`.

What do you think of that ?

**Comment by loganto** [comment]
> As a consequence, if you do not mind, I would like to correct this issue in the scope of the new architecture, which should be ready in few weeks. In the mean time, you should make a correction from your side: do not mount directly domains.conf, use the directory /etc/letsencrypt

Oh  ya - absolutely!  I'll just put domains.conf in the same directory for now  - not a big deal :)  
Also just wanted to say thank you for making this project available to community -> it made setting up letsencrypt so much easier for me. Can't wait for V3 :wink: !
