### ISSUE TITLE
Different Domains

### ISSUE THREAD

**Issue by MightyS33** [adferrand/docker-letsencrypt-dns#64]
If I specify different domains in domains.conf, all certificates are created, but the TXT entries in the respective domains are missing.

> \# domains.conf example:
> *.domain1.com domain1.com
> *.domain2.com domain2.com
> *.domain3.com domain3.com
> ...

If I enter only a single domain like one of the above, everything works great. I could observe that TXT entries appear during the process. When the process is over, they disappear again.

Any idea what I could have done wrong?

**Comment by adferrand** [comment]
Well, if I understand correctly your situation, in fact it is normal. Once the certificate has been issued, a cleanup process is invoked in order to remove all TXT entries that have been inserted to validate the challenge. They will not be used, ever. On the next renewal, unpredictable new tokens will need to be inserted.

So you can expect that all TXT entries disappear.in fact, it is the contrary that would not be normal.

**Comment by MightyS33** [comment]
Edit: When one domain is ready and the next one is processing, the TXT entries of the previous domain disappear. Sometimes the TXT entry of the first domain remains.

**Comment by adferrand** [comment]
Hello again @MightyS33: so let's be clear. You get the certificates you expected ? If so, the DNS challenges have been processed as expected, and so the TXT entries have been added correctly.

What you first describe in your edit seems quite normal for me: Certbot will call a cleanup process at the end of one line, when the expected certificate has been obtained. So you can expect, during the processing of several domains, to have only two TXT entries at a given time for your situation: the token for the extended subdomains, and another one for the domain itself, for the domain that is currently processed (e.g. `domain1.com`).

What is not normal however, is to have TXT entries that remain. This indicate a cleanup process that failed (for any reason, like API timeout, too much calls ...). Certbot will in this case throw an error, but my Docker continue anyway the process, because I think in this context that the most important thing is to get as much as certificates possible, since each of them is generally associated to one critical function of your server. Failures can be dealt from logs afterwards.

**Comment by MightyS33** [comment]
Thank you for your reply. After I have dealt with the process more closely, everything has become clear to me. Everything works great. Thank you for this great docker service!
